/**
 * The full menu tree — spec 01 §3.
 *
 * Every item Photoshop has (minus the deliberate non-goals listed in the spec) appears here,
 * in the same menu, in the same order, with the same shortcut. Items whose command does not
 * exist yet are present but disabled, which is what makes the M1 exit criterion testable: a
 * Photoshop user can go looking for anything and find it where they expect.
 *
 * `cmd` is the command id the command bus will dispatch. `done: true` marks the ones wired up
 * today; everything else renders greyed.
 */

import { FILTER_BY_ID } from '@umbra/engine';

/** A Filter-menu leaf, enabled exactly when the filter registry implements it. */
const filterItem = (label: string, cmd: string): MenuNode => (FILTER_BY_ID.has(cmd) ? { label, cmd, done: true } : { label, cmd });

export interface MenuNode {
  /** Divider line; no other field applies. */
  separator?: true;
  label?: string;
  /** Command id dispatched on click. */
  cmd?: string;
  /** Display shortcut, e.g. "Ctrl+Shift+N". */
  shortcut?: string;
  /** Submenu. */
  items?: MenuNode[];
  /** Implemented and clickable. */
  done?: true;
  /** Shows a check mark; the app supplies live state by id. */
  checkable?: true;
  /** Opens a dialog (renders the "…" affordance is already in the label). */
  dialog?: true;
}

export interface MenuDef {
  label: string;
  items: MenuNode[];
}

const sep: MenuNode = { separator: true };

export const MENUS: MenuDef[] = [
  {
    label: 'File',
    items: [
      { label: 'New…', cmd: 'file.new', shortcut: 'Ctrl+N', dialog: true, done: true },
      { label: 'Open…', cmd: 'file.open', shortcut: 'Ctrl+O', done: true },
      { label: 'Open As…', cmd: 'file.openAs', shortcut: 'Ctrl+Alt+Shift+O' },
      { label: 'Open as Smart Object…', cmd: 'file.openAsSmartObject', done: true },
      { label: 'Open Recent', items: [{ label: '(no recent files)' }, sep, { label: 'Clear Recent File List', cmd: 'file.clearRecent' }] },
      sep,
      { label: 'Close', cmd: 'file.close', shortcut: 'Ctrl+W', done: true },
      { label: 'Close All', cmd: 'file.closeAll', shortcut: 'Ctrl+Alt+W', done: true },
      { label: 'Close Others', cmd: 'file.closeOthers', shortcut: 'Ctrl+Alt+P' },
      { label: 'Save', cmd: 'file.save', shortcut: 'Ctrl+S', done: true },
      { label: 'Save As…', cmd: 'file.saveAs', shortcut: 'Ctrl+Shift+S', done: true },
      { label: 'Save a Copy…', cmd: 'file.saveCopy', shortcut: 'Ctrl+Alt+S', done: true },
      { label: 'Revert', cmd: 'file.revert', shortcut: 'F12' },
      sep,
      {
        label: 'Export',
        items: [
          { label: 'Quick Export as PNG', cmd: 'file.quickExport' },
          { label: 'Export As…', cmd: 'file.exportAs', shortcut: 'Ctrl+Alt+Shift+W' },
          { label: 'Export Preferences…', cmd: 'file.exportPrefs' },
          sep,
          { label: 'Save for Web (Legacy)…', cmd: 'file.saveForWeb', shortcut: 'Ctrl+Alt+Shift+S' },
          sep,
          { label: 'Artboards to Files…', cmd: 'file.artboardsToFiles' },
          { label: 'Artboards to PDF…', cmd: 'file.artboardsToPdf' },
          { label: 'Layers to Files…', cmd: 'file.layersToFiles' },
          { label: 'Layer Comps to Files…', cmd: 'file.layerCompsToFiles' },
          { label: 'Layer Comps to PDF…', cmd: 'file.layerCompsToPdf' },
          sep,
          { label: 'Color Lookup Tables…', cmd: 'file.exportLuts' },
          { label: 'Paths to SVG…', cmd: 'file.pathsToSvg' },
        ],
      },
      sep,
      { label: 'Place Embedded…', cmd: 'file.placeEmbedded', done: true },
      { label: 'Place Linked…', cmd: 'file.placeLinked' },
      { label: 'Package…', cmd: 'file.package' },
      sep,
      {
        label: 'Automate',
        items: [
          { label: 'Batch…', cmd: 'automate.batch' },
          { label: 'PDF Presentation…', cmd: 'automate.pdfPresentation' },
          { label: 'Crop and Straighten Photos', cmd: 'automate.cropStraighten' },
          { label: 'Contact Sheet II…', cmd: 'automate.contactSheet' },
          { label: 'Conditional Mode Change…', cmd: 'automate.conditionalMode' },
          { label: 'Fit Image…', cmd: 'automate.fitImage' },
          { label: 'Lens Correction…', cmd: 'automate.lensCorrection' },
          { label: 'Merge to HDR Pro…', cmd: 'automate.mergeHdr' },
          { label: 'Photomerge…', cmd: 'automate.photomerge' },
        ],
      },
      {
        label: 'Scripts',
        items: [
          { label: 'Image Processor…', cmd: 'scripts.imageProcessor' },
          { label: 'Delete All Empty Layers', cmd: 'scripts.deleteEmptyLayers' },
          { label: 'Flatten All Layer Effects', cmd: 'scripts.flattenEffects' },
          { label: 'Flatten All Masks', cmd: 'scripts.flattenMasks' },
          { label: 'Script Events Manager…', cmd: 'scripts.eventsManager' },
          { label: 'Load Files into Stack…', cmd: 'scripts.loadIntoStack' },
          { label: 'Statistics…', cmd: 'scripts.statistics' },
          sep,
          { label: 'Browse…', cmd: 'scripts.browse' },
        ],
      },
      {
        label: 'Import',
        items: [
          { label: 'Variable Data Sets…', cmd: 'import.variableDataSets' },
          { label: 'Video Frames to Layers…', cmd: 'import.videoFrames' },
          { label: 'Notes…', cmd: 'import.notes' },
        ],
      },
      sep,
      { label: 'File Info…', cmd: 'file.info', shortcut: 'Ctrl+Alt+Shift+I' },
      sep,
      { label: 'Print…', cmd: 'file.print', shortcut: 'Ctrl+P' },
      { label: 'Print One Copy', cmd: 'file.printOne', shortcut: 'Ctrl+Alt+Shift+P' },
      sep,
      { label: 'Exit', cmd: 'file.exit', shortcut: 'Ctrl+Q', done: true },
    ],
  },
  {
    label: 'Edit',
    items: [
      { label: 'Undo', cmd: 'edit.undo', shortcut: 'Ctrl+Z', done: true },
      { label: 'Redo', cmd: 'edit.redo', shortcut: 'Ctrl+Shift+Z', done: true },
      { label: 'Toggle Last State', cmd: 'edit.toggleLastState', shortcut: 'Ctrl+Alt+Z', done: true },
      { label: 'Fade…', cmd: 'edit.fade', shortcut: 'Ctrl+Shift+F', done: true },
      sep,
      { label: 'Cut', cmd: 'edit.cut', shortcut: 'Ctrl+X', done: true },
      { label: 'Copy', cmd: 'edit.copy', shortcut: 'Ctrl+C', done: true },
      { label: 'Copy Merged', cmd: 'edit.copyMerged', shortcut: 'Ctrl+Shift+C', done: true },
      { label: 'Paste', cmd: 'edit.paste', shortcut: 'Ctrl+V', done: true },
      {
        label: 'Paste Special',
        items: [
          { label: 'Paste without Formatting', cmd: 'edit.pastePlain' },
          { label: 'Paste in Place', cmd: 'edit.pasteInPlace', shortcut: 'Ctrl+Shift+V', done: true },
          { label: 'Paste Into', cmd: 'edit.pasteInto', shortcut: 'Ctrl+Alt+Shift+V', done: true },
          { label: 'Paste Outside', cmd: 'edit.pasteOutside', done: true },
        ],
      },
      { label: 'Clear', cmd: 'edit.clear', done: true },
      sep,
      { label: 'Search', cmd: 'edit.search', shortcut: 'Ctrl+F' },
      { label: 'Check Spelling…', cmd: 'edit.checkSpelling' },
      { label: 'Find and Replace Text…', cmd: 'edit.findReplace' },
      sep,
      { label: 'Fill…', cmd: 'edit.fill', shortcut: 'Shift+F5', dialog: true, done: true },
      { label: 'Stroke…', cmd: 'edit.stroke', dialog: true, done: true },
      sep,
      { label: 'Content-Aware Fill…', cmd: 'edit.contentAwareFill' },
      { label: 'Content-Aware Scale', cmd: 'edit.contentAwareScale', shortcut: 'Ctrl+Alt+Shift+C' },
      { label: 'Puppet Warp', cmd: 'edit.puppetWarp' },
      { label: 'Perspective Warp', cmd: 'edit.perspectiveWarp' },
      { label: 'Free Transform', cmd: 'edit.freeTransform', shortcut: 'Ctrl+T', done: true },
      {
        label: 'Transform',
        items: [
          { label: 'Again', cmd: 'transform.again', shortcut: 'Ctrl+Shift+T', done: true },
          sep,
          { label: 'Scale', cmd: 'transform.scale', done: true },
          { label: 'Rotate', cmd: 'transform.rotate', done: true },
          { label: 'Skew', cmd: 'transform.skew', done: true },
          { label: 'Distort', cmd: 'transform.distort' },
          { label: 'Perspective', cmd: 'transform.perspective' },
          { label: 'Warp', cmd: 'transform.warp' },
          sep,
          { label: 'Split Warp Horizontally', cmd: 'transform.splitWarpH' },
          { label: 'Split Warp Vertically', cmd: 'transform.splitWarpV' },
          { label: 'Split Warp Crosswise', cmd: 'transform.splitWarpCross' },
          { label: 'Remove Warp Split', cmd: 'transform.removeWarpSplit' },
          sep,
          { label: 'Rotate 180°', cmd: 'transform.rotate180', done: true },
          { label: 'Rotate 90° Clockwise', cmd: 'transform.rotate90cw', done: true },
          { label: 'Rotate 90° Counter Clockwise', cmd: 'transform.rotate90ccw', done: true },
          sep,
          { label: 'Flip Horizontal', cmd: 'transform.flipH', done: true },
          { label: 'Flip Vertical', cmd: 'transform.flipV', done: true },
        ],
      },
      sep,
      { label: 'Auto-Align Layers…', cmd: 'edit.autoAlign' },
      { label: 'Auto-Blend Layers…', cmd: 'edit.autoBlend' },
      { label: 'Sky Replacement…', cmd: 'edit.skyReplacement' },
      sep,
      { label: 'Define Brush Preset…', cmd: 'edit.defineBrush' },
      { label: 'Define Pattern…', cmd: 'edit.definePattern', done: true },
      { label: 'Define Custom Shape…', cmd: 'edit.defineShape' },
      sep,
      {
        label: 'Purge',
        items: [
          { label: 'Clipboard', cmd: 'purge.clipboard' },
          { label: 'Histories', cmd: 'purge.histories' },
          sep,
          { label: 'All', cmd: 'purge.all' },
        ],
      },
      {
        label: 'Presets',
        items: [
          { label: 'Preset Manager…', cmd: 'presets.manager' },
          sep,
          { label: 'Export/Import Presets…', cmd: 'presets.exportImport' },
        ],
      },
      sep,
      { label: 'Color Settings…', cmd: 'edit.colorSettings', shortcut: 'Ctrl+Shift+K', dialog: true },
      { label: 'Assign Profile…', cmd: 'edit.assignProfile' },
      { label: 'Convert to Profile…', cmd: 'edit.convertProfile' },
      sep,
      { label: 'Keyboard Shortcuts…', cmd: 'edit.keyboardShortcuts', shortcut: 'Ctrl+Alt+Shift+K' },
      { label: 'Menus…', cmd: 'edit.menus', shortcut: 'Ctrl+Alt+Shift+M' },
      { label: 'Toolbar…', cmd: 'edit.toolbar' },
      {
        label: 'Preferences',
        items: [
          { label: 'General…', cmd: 'prefs.general', shortcut: 'Ctrl+K', done: true },
          { label: 'Interface…', cmd: 'prefs.interface', done: true },
          { label: 'Workspace…', cmd: 'prefs.workspace' },
          { label: 'Tools…', cmd: 'prefs.tools' },
          { label: 'Performance…', cmd: 'prefs.performance' },
          { label: 'Scratch Disks…', cmd: 'prefs.scratch' },
          { label: 'Cursors…', cmd: 'prefs.cursors' },
          { label: 'Transparency & Gamut…', cmd: 'prefs.transparency' },
          { label: 'Units & Rulers…', cmd: 'prefs.units' },
          { label: 'Guides, Grid & Slices…', cmd: 'prefs.guides' },
          { label: 'Type…', cmd: 'prefs.type' },
          { label: 'File Handling…', cmd: 'prefs.fileHandling' },
          { label: 'Export…', cmd: 'prefs.export' },
        ],
      },
    ],
  },
  {
    label: 'Image',
    items: [
      {
        label: 'Mode',
        items: [
          { label: 'Bitmap', cmd: 'mode.bitmap' },
          { label: 'Grayscale', cmd: 'mode.grayscale' },
          { label: 'Duotone', cmd: 'mode.duotone' },
          { label: 'Indexed Color…', cmd: 'mode.indexed' },
          { label: 'RGB Color', cmd: 'mode.rgb', checkable: true },
          { label: 'CMYK Color', cmd: 'mode.cmyk' },
          { label: 'Lab Color', cmd: 'mode.lab' },
          { label: 'Multichannel', cmd: 'mode.multichannel' },
          sep,
          { label: '8 Bits/Channel', cmd: 'mode.depth8', checkable: true },
          { label: '16 Bits/Channel', cmd: 'mode.depth16' },
          { label: '32 Bits/Channel', cmd: 'mode.depth32' },
          sep,
          { label: 'Color Table…', cmd: 'mode.colorTable' },
        ],
      },
      {
        label: 'Adjustments',
        items: [
          { label: 'Brightness/Contrast…', cmd: 'adjust.brightnessContrast', done: true },
          { label: 'Levels…', cmd: 'adjust.levels', shortcut: 'Ctrl+L', done: true },
          { label: 'Curves…', cmd: 'adjust.curves', shortcut: 'Ctrl+M', done: true },
          { label: 'Exposure…', cmd: 'adjust.exposure', done: true },
          sep,
          { label: 'Vibrance…', cmd: 'adjust.vibrance', done: true },
          { label: 'Hue/Saturation…', cmd: 'adjust.hueSaturation', shortcut: 'Ctrl+U', done: true },
          { label: 'Color Balance…', cmd: 'adjust.colorBalance', shortcut: 'Ctrl+B', done: true },
          { label: 'Black & White…', cmd: 'adjust.blackWhite', shortcut: 'Ctrl+Alt+Shift+B', done: true },
          { label: 'Photo Filter…', cmd: 'adjust.photoFilter', done: true },
          { label: 'Channel Mixer…', cmd: 'adjust.channelMixer', done: true },
          { label: 'Color Lookup…', cmd: 'adjust.colorLookup', done: true },
          sep,
          { label: 'Invert', cmd: 'adjust.invert', shortcut: 'Ctrl+I', done: true },
          { label: 'Posterize…', cmd: 'adjust.posterize', done: true },
          { label: 'Threshold…', cmd: 'adjust.threshold', done: true },
          { label: 'Gradient Map…', cmd: 'adjust.gradientMap', done: true },
          { label: 'Selective Color…', cmd: 'adjust.selectiveColor', done: true },
          sep,
          { label: 'Shadows/Highlights…', cmd: 'adjust.shadowsHighlights', done: true },
          { label: 'HDR Toning…', cmd: 'adjust.hdrToning', done: true },
          sep,
          { label: 'Desaturate', cmd: 'adjust.desaturate', shortcut: 'Ctrl+Shift+U', done: true },
          { label: 'Match Color…', cmd: 'adjust.matchColor', done: true },
          { label: 'Replace Color…', cmd: 'adjust.replaceColor', done: true },
          { label: 'Equalize', cmd: 'adjust.equalize', done: true },
        ],
      },
      sep,
      { label: 'Auto Tone', cmd: 'image.autoTone', shortcut: 'Ctrl+Shift+L', done: true },
      { label: 'Auto Contrast', cmd: 'image.autoContrast', shortcut: 'Ctrl+Alt+Shift+L', done: true },
      { label: 'Auto Color', cmd: 'image.autoColor', shortcut: 'Ctrl+Shift+B', done: true },
      sep,
      { label: 'Image Size…', cmd: 'image.imageSize', shortcut: 'Ctrl+Alt+I', dialog: true, done: true },
      { label: 'Canvas Size…', cmd: 'image.canvasSize', shortcut: 'Ctrl+Alt+C', dialog: true, done: true },
      {
        label: 'Image Rotation',
        items: [
          { label: '180°', cmd: 'image.rotate180', done: true },
          { label: '90° Clockwise', cmd: 'image.rotate90cw', done: true },
          { label: '90° Counter Clockwise', cmd: 'image.rotate90ccw', done: true },
          { label: 'Arbitrary…', cmd: 'image.rotateArbitrary' },
          sep,
          { label: 'Flip Canvas Horizontal', cmd: 'image.flipH', done: true },
          { label: 'Flip Canvas Vertical', cmd: 'image.flipV', done: true },
        ],
      },
      { label: 'Crop', cmd: 'image.crop', done: true },
      { label: 'Trim…', cmd: 'image.trim', done: true },
      { label: 'Reveal All', cmd: 'image.revealAll', done: true },
      sep,
      { label: 'Duplicate…', cmd: 'image.duplicate' },
      { label: 'Apply Image…', cmd: 'image.applyImage', done: true },
      { label: 'Calculations…', cmd: 'image.calculations', done: true },
      sep,
      { label: 'Variables', items: [{ label: 'Define…', cmd: 'variables.define' }, { label: 'Data Sets…', cmd: 'variables.dataSets' }] },
      { label: 'Apply Data Set…', cmd: 'image.applyDataSet' },
      sep,
      { label: 'Analysis', items: [{ label: 'Set Measurement Scale', cmd: 'analysis.scale' }, { label: 'Record Measurements', cmd: 'analysis.record' }] },
    ],
  },
  {
    label: 'Layer',
    items: [
      {
        label: 'New',
        items: [
          { label: 'Layer…', cmd: 'layer.new', shortcut: 'Ctrl+Shift+N', done: true },
          { label: 'Layer from Background…', cmd: 'layer.fromBackground' },
          { label: 'Group…', cmd: 'layer.newGroup' },
          { label: 'Group from Layers…', cmd: 'layer.groupFromLayers' },
          { label: 'Artboard…', cmd: 'layer.newArtboard' },
          { label: 'Artboard from Group…', cmd: 'layer.artboardFromGroup' },
          { label: 'Artboard from Layers…', cmd: 'layer.artboardFromLayers' },
          { label: 'Frame from Layers…', cmd: 'layer.frameFromLayers' },
          sep,
          { label: 'Layer Via Copy', cmd: 'layer.viaCopy', shortcut: 'Ctrl+J', done: true },
          { label: 'Layer Via Cut', cmd: 'layer.viaCut', shortcut: 'Ctrl+Shift+J', done: true },
        ],
      },
      { label: 'Copy CSS', cmd: 'layer.copyCss' },
      { label: 'Copy SVG', cmd: 'layer.copySvg' },
      { label: 'Duplicate Layer…', cmd: 'layer.duplicate', done: true },
      { label: 'Delete', items: [{ label: 'Layer', cmd: 'layer.delete', done: true }, { label: 'Hidden Layers', cmd: 'layer.deleteHidden' }] },
      sep,
      { label: 'Quick Export as PNG', cmd: 'layer.quickExport' },
      { label: 'Export As…', cmd: 'layer.exportAs' },
      sep,
      { label: 'Rename Layer…', cmd: 'layer.rename', done: true },
      {
        label: 'Layer Style',
        items: [
          { label: 'Blending Options…', cmd: 'style.blendingOptions' },
          sep,
          { label: 'Bevel & Emboss…', cmd: 'style.bevelEmboss' },
          { label: 'Stroke…', cmd: 'style.stroke' },
          { label: 'Inner Shadow…', cmd: 'style.innerShadow' },
          { label: 'Inner Glow…', cmd: 'style.innerGlow' },
          { label: 'Satin…', cmd: 'style.satin' },
          { label: 'Color Overlay…', cmd: 'style.colorOverlay' },
          { label: 'Gradient Overlay…', cmd: 'style.gradientOverlay' },
          { label: 'Pattern Overlay…', cmd: 'style.patternOverlay' },
          { label: 'Outer Glow…', cmd: 'style.outerGlow' },
          { label: 'Drop Shadow…', cmd: 'style.dropShadow' },
          sep,
          { label: 'Copy Layer Style', cmd: 'style.copy' },
          { label: 'Paste Layer Style', cmd: 'style.paste' },
          { label: 'Clear Layer Style', cmd: 'style.clear' },
          sep,
          { label: 'Global Light…', cmd: 'style.globalLight' },
          { label: 'Create Layers', cmd: 'style.createLayers' },
          { label: 'Hide All Effects', cmd: 'style.hideAll' },
          { label: 'Scale Effects…', cmd: 'style.scaleEffects' },
        ],
      },
      { label: 'Smart Filter', items: [{ label: 'Disable Smart Filters', cmd: 'smartFilter.disable', done: true }, { label: 'Delete Filter Mask', cmd: 'smartFilter.deleteMask', done: true }, { label: 'Clear Smart Filters', cmd: 'smartFilter.clear', done: true }] },
      sep,
      {
        label: 'New Fill Layer',
        items: [
          { label: 'Solid Color…', cmd: 'fill.solid', done: true },
          { label: 'Gradient…', cmd: 'fill.gradient', done: true },
          { label: 'Pattern…', cmd: 'fill.pattern', done: true },
        ],
      },
      {
        label: 'New Adjustment Layer',
        items: [
          { label: 'Brightness/Contrast…', cmd: 'adjLayer.brightnessContrast', done: true },
          { label: 'Levels…', cmd: 'adjLayer.levels', done: true },
          { label: 'Curves…', cmd: 'adjLayer.curves', done: true },
          { label: 'Exposure…', cmd: 'adjLayer.exposure', done: true },
          sep,
          { label: 'Vibrance…', cmd: 'adjLayer.vibrance', done: true },
          { label: 'Hue/Saturation…', cmd: 'adjLayer.hueSaturation', done: true },
          { label: 'Color Balance…', cmd: 'adjLayer.colorBalance', done: true },
          { label: 'Black & White…', cmd: 'adjLayer.blackWhite', done: true },
          { label: 'Photo Filter…', cmd: 'adjLayer.photoFilter', done: true },
          { label: 'Channel Mixer…', cmd: 'adjLayer.channelMixer', done: true },
          { label: 'Color Lookup…', cmd: 'adjLayer.colorLookup', done: true },
          sep,
          { label: 'Invert', cmd: 'adjLayer.invert', done: true },
          { label: 'Posterize…', cmd: 'adjLayer.posterize', done: true },
          { label: 'Threshold…', cmd: 'adjLayer.threshold', done: true },
          { label: 'Gradient Map…', cmd: 'adjLayer.gradientMap', done: true },
          { label: 'Selective Color…', cmd: 'adjLayer.selectiveColor', done: true },
        ],
      },
      { label: 'Layer Content Options…', cmd: 'layer.contentOptions' },
      sep,
      {
        label: 'Layer Mask',
        items: [
          { label: 'Reveal All', cmd: 'mask.revealAll', done: true },
          { label: 'Hide All', cmd: 'mask.hideAll', done: true },
          { label: 'Reveal Selection', cmd: 'mask.revealSelection', done: true },
          { label: 'Hide Selection', cmd: 'mask.hideSelection', done: true },
          { label: 'From Transparency', cmd: 'mask.fromTransparency', done: true },
          sep,
          { label: 'Delete', cmd: 'mask.delete', done: true },
          { label: 'Apply', cmd: 'mask.apply', done: true },
          sep,
          { label: 'Enable', cmd: 'mask.enable', done: true },
          { label: 'Link', cmd: 'mask.link' },
        ],
      },
      {
        label: 'Vector Mask',
        items: [
          { label: 'Reveal All', cmd: 'vmask.revealAll' },
          { label: 'Hide All', cmd: 'vmask.hideAll' },
          { label: 'Current Path', cmd: 'vmask.currentPath' },
          sep,
          { label: 'Delete', cmd: 'vmask.delete' },
          { label: 'Enable', cmd: 'vmask.enable' },
          { label: 'Link', cmd: 'vmask.link' },
        ],
      },
      { label: 'Create Clipping Mask', cmd: 'layer.clippingMask', shortcut: 'Ctrl+Alt+G', done: true },
      { label: 'Mask All Objects', cmd: 'layer.maskAllObjects' },
      sep,
      {
        label: 'Smart Objects',
        items: [
          { label: 'Convert to Smart Object', cmd: 'so.convert', done: true },
          { label: 'New Smart Object via Copy', cmd: 'so.newViaCopy', done: true },
          sep,
          { label: 'Edit Contents', cmd: 'so.editContents', done: true },
          { label: 'Update Modified Content', cmd: 'so.updateModified' },
          { label: 'Update All Modified Content', cmd: 'so.updateAll' },
          { label: 'Relink to File…', cmd: 'so.relink' },
          { label: 'Replace Contents…', cmd: 'so.replaceContents' },
          { label: 'Export Contents…', cmd: 'so.exportContents' },
          sep,
          { label: 'Embed Linked', cmd: 'so.embedLinked' },
          { label: 'Embed All Linked', cmd: 'so.embedAllLinked' },
          { label: 'Convert to Linked…', cmd: 'so.convertToLinked' },
          sep,
          { label: 'Stack Mode', items: [{ label: 'Mean', cmd: 'so.stackMean' }, { label: 'Median', cmd: 'so.stackMedian' }, { label: 'Maximum', cmd: 'so.stackMax' }, { label: 'Minimum', cmd: 'so.stackMin' }] },
          { label: 'Convert to Layers', cmd: 'so.convertToLayers', done: true },
          { label: 'Rasterize', cmd: 'so.rasterize', done: true },
        ],
      },
      {
        label: 'Rasterize',
        items: [
          { label: 'Type', cmd: 'rasterize.type' },
          { label: 'Shape', cmd: 'rasterize.shape' },
          { label: 'Fill Content', cmd: 'rasterize.fillContent' },
          { label: 'Vector Mask', cmd: 'rasterize.vectorMask' },
          { label: 'Smart Object', cmd: 'rasterize.smartObject', done: true },
          { label: 'Layer Style', cmd: 'rasterize.layerStyle' },
          sep,
          { label: 'Layer', cmd: 'rasterize.layer' },
          { label: 'All Layers', cmd: 'rasterize.allLayers' },
        ],
      },
      { label: 'New Layer Based Slice', cmd: 'layer.newSlice' },
      sep,
      { label: 'Group Layers', cmd: 'layer.group', shortcut: 'Ctrl+G', done: true },
      { label: 'Ungroup Layers', cmd: 'layer.ungroup', shortcut: 'Ctrl+Shift+G', done: true },
      { label: 'Hide Layers', cmd: 'layer.hide', shortcut: 'Ctrl+,' },
      sep,
      {
        label: 'Arrange',
        items: [
          { label: 'Bring to Front', cmd: 'arrange.front', shortcut: 'Ctrl+Shift+]' },
          { label: 'Bring Forward', cmd: 'arrange.forward', shortcut: 'Ctrl+]', done: true },
          { label: 'Send Backward', cmd: 'arrange.backward', shortcut: 'Ctrl+[', done: true },
          { label: 'Send to Back', cmd: 'arrange.back', shortcut: 'Ctrl+Shift+[' },
          sep,
          { label: 'Reverse', cmd: 'arrange.reverse' },
        ],
      },
      { label: 'Combine Shapes', items: [{ label: 'Unite Shapes', cmd: 'shape.unite' }, { label: 'Subtract Front Shape', cmd: 'shape.subtract' }, { label: 'Intersect Shape Areas', cmd: 'shape.intersect' }, { label: 'Exclude Overlapping Shapes', cmd: 'shape.exclude' }, sep, { label: 'Merge Shape Components', cmd: 'shape.merge' }] },
      { label: 'Align', items: [{ label: 'Top Edges', cmd: 'align.top' }, { label: 'Vertical Centers', cmd: 'align.vcenter' }, { label: 'Bottom Edges', cmd: 'align.bottom' }, sep, { label: 'Left Edges', cmd: 'align.left' }, { label: 'Horizontal Centers', cmd: 'align.hcenter' }, { label: 'Right Edges', cmd: 'align.right' }] },
      { label: 'Distribute', items: [{ label: 'Top Edges', cmd: 'distribute.top' }, { label: 'Vertical Centers', cmd: 'distribute.vcenter' }, { label: 'Bottom Edges', cmd: 'distribute.bottom' }, sep, { label: 'Left Edges', cmd: 'distribute.left' }, { label: 'Horizontal Centers', cmd: 'distribute.hcenter' }, { label: 'Right Edges', cmd: 'distribute.right' }] },
      sep,
      { label: 'Lock Layers…', cmd: 'layer.lock', shortcut: 'Ctrl+/' },
      { label: 'Link Layers', cmd: 'layer.link' },
      { label: 'Select Linked Layers', cmd: 'layer.selectLinked' },
      sep,
      { label: 'Merge Down', cmd: 'layer.mergeDown', shortcut: 'Ctrl+E', done: true },
      { label: 'Merge Visible', cmd: 'layer.mergeVisible', shortcut: 'Ctrl+Shift+E', done: true },
      { label: 'Flatten Image', cmd: 'layer.flatten', done: true },
      sep,
      { label: 'Matting', items: [{ label: 'Color Decontaminate…', cmd: 'matting.decontaminate' }, { label: 'Defringe…', cmd: 'matting.defringe' }, { label: 'Remove Black Matte', cmd: 'matting.removeBlack' }, { label: 'Remove White Matte', cmd: 'matting.removeWhite' }] },
    ],
  },
  {
    label: 'Type',
    items: [
      {
        label: 'Panels',
        items: [
          { label: 'Character Panel', cmd: 'panel.character' },
          { label: 'Paragraph Panel', cmd: 'panel.paragraph' },
          { label: 'Glyphs Panel', cmd: 'panel.glyphs' },
          { label: 'Character Styles Panel', cmd: 'panel.characterStyles' },
          { label: 'Paragraph Styles Panel', cmd: 'panel.paragraphStyles' },
        ],
      },
      {
        label: 'Anti-Alias',
        items: [
          { label: 'None', cmd: 'type.aaNone' },
          { label: 'Sharp', cmd: 'type.aaSharp' },
          { label: 'Crisp', cmd: 'type.aaCrisp' },
          { label: 'Strong', cmd: 'type.aaStrong' },
          { label: 'Smooth', cmd: 'type.aaSmooth' },
        ],
      },
      { label: 'Orientation', items: [{ label: 'Horizontal', cmd: 'type.horizontal' }, { label: 'Vertical', cmd: 'type.vertical' }] },
      { label: 'OpenType', items: [{ label: 'Standard Ligatures', cmd: 'type.otLiga' }, { label: 'Discretionary Ligatures', cmd: 'type.otDlig' }, { label: 'Swash', cmd: 'type.otSwsh' }, { label: 'Oldstyle', cmd: 'type.otOnum' }, { label: 'Fractions', cmd: 'type.otFrac' }, { label: 'Ordinals', cmd: 'type.otOrdn' }, { label: 'Stylistic Alternates', cmd: 'type.otSalt' }, { label: 'Titling Alternates', cmd: 'type.otTitl' }] },
      sep,
      { label: 'Create Work Path', cmd: 'type.createWorkPath' },
      { label: 'Convert to Shape', cmd: 'type.convertToShape' },
      { label: 'Rasterize Type Layer', cmd: 'type.rasterize' },
      { label: 'Convert to Paragraph Text', cmd: 'type.toParagraph' },
      sep,
      { label: 'Warp Text…', cmd: 'type.warp' },
      { label: 'Match Font…', cmd: 'type.matchFont' },
      { label: 'Font Preview Size', items: [{ label: 'None', cmd: 'type.previewNone' }, { label: 'Small', cmd: 'type.previewSmall' }, { label: 'Medium', cmd: 'type.previewMedium' }, { label: 'Large', cmd: 'type.previewLarge' }, { label: 'Huge', cmd: 'type.previewHuge' }] },
      { label: 'Language Options', items: [{ label: 'Default', cmd: 'type.langDefault' }, { label: 'Middle Eastern Features', cmd: 'type.langMiddleEast' }, { label: 'East Asian Features', cmd: 'type.langEastAsian' }] },
      sep,
      { label: 'Update All Text Layers', cmd: 'type.updateAll' },
      { label: 'Resolve Missing Fonts…', cmd: 'type.resolveMissing' },
      { label: 'Paste Lorem Ipsum', cmd: 'type.loremIpsum' },
      sep,
      { label: 'Load Default Type Styles', cmd: 'type.loadDefaults' },
      { label: 'Save Default Type Styles', cmd: 'type.saveDefaults' },
    ],
  },
  {
    label: 'Select',
    items: [
      { label: 'All', cmd: 'select.all', shortcut: 'Ctrl+A', done: true },
      { label: 'Deselect', cmd: 'select.deselect', shortcut: 'Ctrl+D', done: true },
      { label: 'Reselect', cmd: 'select.reselect', shortcut: 'Ctrl+Shift+D', done: true },
      { label: 'Inverse', cmd: 'select.inverse', shortcut: 'Ctrl+Shift+I', done: true },
      sep,
      { label: 'All Layers', cmd: 'select.allLayers', shortcut: 'Ctrl+Alt+A' },
      { label: 'Deselect Layers', cmd: 'select.deselectLayers' },
      { label: 'Find Layers', cmd: 'select.findLayers', shortcut: 'Ctrl+Alt+Shift+F' },
      { label: 'Isolate Layers', cmd: 'select.isolateLayers' },
      sep,
      { label: 'Color Range…', cmd: 'select.colorRange' },
      { label: 'Focus Area…', cmd: 'select.focusArea' },
      { label: 'Subject', cmd: 'select.subject' },
      { label: 'Sky', cmd: 'select.sky' },
      sep,
      { label: 'Select and Mask…', cmd: 'select.selectAndMask', shortcut: 'Ctrl+Alt+R' },
      sep,
      {
        label: 'Modify',
        items: [
          { label: 'Border…', cmd: 'modify.border', done: true },
          { label: 'Smooth…', cmd: 'modify.smooth', done: true },
          { label: 'Expand…', cmd: 'modify.expand', done: true },
          { label: 'Contract…', cmd: 'modify.contract', done: true },
          { label: 'Feather…', cmd: 'modify.feather', shortcut: 'Shift+F6', done: true },
        ],
      },
      sep,
      { label: 'Grow', cmd: 'select.grow', done: true },
      { label: 'Similar', cmd: 'select.similar', done: true },
      sep,
      { label: 'Transform Selection', cmd: 'select.transformSelection', done: true },
      sep,
      { label: 'Edit in Quick Mask Mode', cmd: 'select.quickMask', shortcut: 'Q', done: true },
      sep,
      { label: 'Load Selection…', cmd: 'select.loadSelection', done: true },
      { label: 'Save Selection…', cmd: 'select.saveSelection', done: true },
    ],
  },
  {
    label: 'Filter',
    items: [
      { label: 'Last Filter', cmd: 'filter.last', shortcut: 'Ctrl+Alt+F', done: true },
      sep,
      { label: 'Convert for Smart Filters', cmd: 'filter.convertForSmart', done: true },
      sep,
      filterItem('Filter Gallery…', 'filter.gallery'),
      { label: 'Adaptive Wide Angle…', cmd: 'filter.adaptiveWideAngle', shortcut: 'Ctrl+Alt+Shift+A' },
      { label: 'Develop…', cmd: 'filter.develop', shortcut: 'Ctrl+Shift+A' },
      { label: 'Lens Correction…', cmd: 'filter.lensCorrection', shortcut: 'Ctrl+Shift+R' },
      { label: 'Liquify…', cmd: 'filter.liquify', shortcut: 'Ctrl+Shift+X' },
      { label: 'Vanishing Point…', cmd: 'filter.vanishingPoint', shortcut: 'Ctrl+Alt+V' },
      sep,
      { label: 'Blur', items: ['Average', 'Blur', 'Blur More', 'Box Blur…', 'Gaussian Blur…', 'Lens Blur…', 'Motion Blur…', 'Radial Blur…', 'Shape Blur…', 'Smart Blur…', 'Surface Blur…'].map((l) => filterItem(l, `blur.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Blur Gallery', items: ['Field Blur…', 'Iris Blur…', 'Tilt-Shift…', 'Path Blur…', 'Spin Blur…'].map((l) => ({ label: l, cmd: `blurGallery.${l.replace(/[^a-z]/gi, '').toLowerCase()}` })) },
      { label: 'Distort', items: ['Displace…', 'Pinch…', 'Polar Coordinates…', 'Ripple…', 'Shear…', 'Spherize…', 'Twirl…', 'Wave…', 'ZigZag…'].map((l) => filterItem(l, `distort.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Noise', items: ['Add Noise…', 'Despeckle', 'Dust & Scratches…', 'Median…', 'Reduce Noise…'].map((l) => filterItem(l, `noise.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Pixelate', items: ['Color Halftone…', 'Crystallize…', 'Facet', 'Fragment', 'Mezzotint…', 'Mosaic…', 'Pointillize…'].map((l) => filterItem(l, `pixelate.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Render', items: ['Flame…', 'Picture Frame…', 'Tree…', 'Clouds', 'Difference Clouds', 'Fibers…', 'Lens Flare…'].map((l) => filterItem(l, `render.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Sharpen', items: ['Sharpen', 'Sharpen Edges', 'Sharpen More', 'Smart Sharpen…', 'Unsharp Mask…'].map((l) => filterItem(l, `sharpen.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Stylize', items: ['Diffuse…', 'Emboss…', 'Extrude…', 'Find Edges', 'Oil Paint…', 'Solarize', 'Tiles…', 'Trace Contour…', 'Wind…'].map((l) => filterItem(l, `stylize.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Video', items: ['De-Interlace…', 'NTSC Colors'].map((l) => filterItem(l, `video.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
      { label: 'Other', items: ['Custom…', 'High Pass…', 'HSB/HSL', 'Maximum…', 'Minimum…', 'Offset…'].map((l) => filterItem(l, `other.${l.replace(/[^a-z]/gi, '').toLowerCase()}`)) },
    ],
  },
  {
    label: 'View',
    items: [
      { label: 'Proof Setup', items: [{ label: 'Custom…', cmd: 'proof.custom' }, sep, { label: 'Working CMYK', cmd: 'proof.workingCmyk' }, { label: 'Monitor RGB', cmd: 'proof.monitorRgb' }, sep, { label: 'Color Blindness — Protanopia', cmd: 'proof.protanopia' }, { label: 'Color Blindness — Deuteranopia', cmd: 'proof.deuteranopia' }] },
      { label: 'Proof Colors', cmd: 'view.proofColors', shortcut: 'Ctrl+Y', checkable: true },
      { label: 'Gamut Warning', cmd: 'view.gamutWarning', shortcut: 'Ctrl+Shift+Y', checkable: true },
      { label: 'Pixel Aspect Ratio', items: [{ label: 'Square', cmd: 'par.square' }, { label: 'Custom Pixel Aspect Ratio…', cmd: 'par.custom' }] },
      { label: '32-bit Preview Options…', cmd: 'view.hdrPreview' },
      sep,
      { label: 'Zoom In', cmd: 'view.zoomIn', shortcut: 'Ctrl++', done: true },
      { label: 'Zoom Out', cmd: 'view.zoomOut', shortcut: 'Ctrl+-', done: true },
      { label: 'Fit on Screen', cmd: 'view.fit', shortcut: 'Ctrl+0', done: true },
      { label: 'Fit Layer(s) on Screen', cmd: 'view.fitLayers' },
      { label: 'Fit Artboard on Screen', cmd: 'view.fitArtboard' },
      { label: '100%', cmd: 'view.actual', shortcut: 'Ctrl+1', done: true },
      { label: '200%', cmd: 'view.zoom200' },
      { label: 'Print Size', cmd: 'view.printSize' },
      sep,
      { label: 'Flip Horizontal', cmd: 'view.flipH', checkable: true },
      { label: 'Pattern Preview', cmd: 'view.patternPreview', checkable: true },
      sep,
      { label: 'Screen Mode', items: [{ label: 'Standard Screen Mode', cmd: 'screen.standard', checkable: true, done: true }, { label: 'Full Screen Mode With Menu Bar', cmd: 'screen.fullMenu', done: true }, { label: 'Full Screen Mode', cmd: 'screen.full', done: true }] },
      sep,
      { label: 'Extras', cmd: 'view.extras', shortcut: 'Ctrl+H', checkable: true, done: true },
      {
        label: 'Show',
        items: [
          { label: 'Layer Edges', cmd: 'show.layerEdges', checkable: true },
          { label: 'Selection Edges', cmd: 'show.selectionEdges', checkable: true },
          { label: 'Target Path', cmd: 'show.targetPath', shortcut: 'Ctrl+Shift+H', checkable: true },
          { label: 'Grid', cmd: 'show.grid', shortcut: "Ctrl+'", checkable: true, done: true },
          { label: 'Guides', cmd: 'show.guides', shortcut: 'Ctrl+;', checkable: true, done: true },
          { label: 'Canvas Guides', cmd: 'show.canvasGuides', checkable: true },
          { label: 'Artboard Guides', cmd: 'show.artboardGuides', checkable: true },
          { label: 'Artboard Names', cmd: 'show.artboardNames', checkable: true },
          { label: 'Count', cmd: 'show.count', checkable: true },
          { label: 'Smart Guides', cmd: 'show.smartGuides', checkable: true },
          { label: 'Slices', cmd: 'show.slices', checkable: true },
          { label: 'Notes', cmd: 'show.notes', checkable: true },
          { label: 'Pixel Grid', cmd: 'show.pixelGrid', checkable: true, done: true },
          { label: 'Brush Preview', cmd: 'show.brushPreview', checkable: true },
          { label: 'Mesh', cmd: 'show.mesh', checkable: true },
          { label: 'Edit Pins', cmd: 'show.editPins', checkable: true },
          sep,
          { label: 'All', cmd: 'show.all' },
          { label: 'None', cmd: 'show.none' },
          sep,
          { label: 'Show Extras Options…', cmd: 'show.options' },
        ],
      },
      sep,
      { label: 'Rulers', cmd: 'view.rulers', shortcut: 'Ctrl+R', checkable: true, done: true },
      sep,
      { label: 'Snap', cmd: 'view.snap', shortcut: 'Ctrl+Shift+;', checkable: true },
      { label: 'Snap To', items: [{ label: 'Guides', cmd: 'snapTo.guides', checkable: true }, { label: 'Grid', cmd: 'snapTo.grid', checkable: true }, { label: 'Layers', cmd: 'snapTo.layers', checkable: true }, { label: 'Slices', cmd: 'snapTo.slices', checkable: true }, { label: 'Document Bounds', cmd: 'snapTo.docBounds', checkable: true }, sep, { label: 'All', cmd: 'snapTo.all' }, { label: 'None', cmd: 'snapTo.none' }] },
      sep,
      { label: 'Lock Guides', cmd: 'view.lockGuides', shortcut: 'Ctrl+Alt+;', checkable: true },
      { label: 'Clear Guides', cmd: 'view.clearGuides' },
      { label: 'Clear Selected Artboard Guides', cmd: 'view.clearArtboardGuides' },
      { label: 'Clear Canvas Guides', cmd: 'view.clearCanvasGuides' },
      { label: 'New Guide…', cmd: 'view.newGuide' },
      { label: 'New Guide Layout…', cmd: 'view.newGuideLayout' },
      { label: 'New Guides From Shape', cmd: 'view.guidesFromShape' },
      sep,
      { label: 'Lock Slices', cmd: 'view.lockSlices' },
      { label: 'Clear Slices', cmd: 'view.clearSlices' },
    ],
  },
  {
    label: 'Window',
    items: [
      {
        label: 'Arrange',
        items: [
          { label: 'Tile All Vertically', cmd: 'arrangeWin.tileV' },
          { label: 'Tile All Horizontally', cmd: 'arrangeWin.tileH' },
          { label: '2-up Vertical', cmd: 'arrangeWin.2upV' },
          { label: '2-up Horizontal', cmd: 'arrangeWin.2upH' },
          { label: '3-up Vertical', cmd: 'arrangeWin.3upV' },
          { label: '4-up', cmd: 'arrangeWin.4up' },
          { label: '6-up', cmd: 'arrangeWin.6up' },
          sep,
          { label: 'Consolidate All to Tabs', cmd: 'arrangeWin.consolidate' },
          { label: 'Cascade', cmd: 'arrangeWin.cascade' },
          { label: 'Float in Window', cmd: 'arrangeWin.float' },
          { label: 'Float All in Windows', cmd: 'arrangeWin.floatAll' },
          sep,
          { label: 'Match Zoom', cmd: 'arrangeWin.matchZoom' },
          { label: 'Match Location', cmd: 'arrangeWin.matchLocation' },
          { label: 'Match Rotation', cmd: 'arrangeWin.matchRotation' },
          { label: 'Match All', cmd: 'arrangeWin.matchAll' },
          sep,
          { label: 'New Window', cmd: 'arrangeWin.newWindow' },
        ],
      },
      {
        label: 'Workspace',
        items: [
          { label: 'Essentials (Default)', cmd: 'workspace.essentials', checkable: true, done: true },
          { label: 'Painting', cmd: 'workspace.painting', done: true },
          { label: 'Photography', cmd: 'workspace.photography', done: true },
          { label: 'Graphic and Web', cmd: 'workspace.graphicWeb', done: true },
          sep,
          { label: 'Reset Essentials', cmd: 'workspace.reset', done: true },
          { label: 'New Workspace…', cmd: 'workspace.new', done: true },
          { label: 'Delete Workspace…', cmd: 'workspace.delete' },
          sep,
          { label: 'Keyboard Shortcuts & Menus…', cmd: 'workspace.shortcutsMenus' },
          { label: 'Lock Workspace', cmd: 'workspace.lock', checkable: true },
        ],
      },
      sep,
      { label: 'Actions', cmd: 'panel.actions', shortcut: 'Alt+F9', checkable: true },
      { label: 'Adjustments', cmd: 'panel.adjustments', checkable: true },
      { label: 'Brush Settings', cmd: 'panel.brushSettings', shortcut: 'F5', checkable: true },
      { label: 'Brushes', cmd: 'panel.brushes', checkable: true },
      { label: 'Channels', cmd: 'panel.channels', checkable: true },
      { label: 'Character', cmd: 'panel.character', checkable: true },
      { label: 'Character Styles', cmd: 'panel.characterStyles', checkable: true },
      { label: 'Clone Source', cmd: 'panel.cloneSource', checkable: true },
      { label: 'Color', cmd: 'panel.color', shortcut: 'F6', checkable: true, done: true },
      { label: 'Glyphs', cmd: 'panel.glyphs', checkable: true },
      { label: 'Gradients', cmd: 'panel.gradients', checkable: true },
      { label: 'Histogram', cmd: 'panel.histogram', checkable: true },
      { label: 'History', cmd: 'panel.history', checkable: true, done: true },
      { label: 'Info', cmd: 'panel.info', shortcut: 'F8', checkable: true, done: true },
      { label: 'Layer Comps', cmd: 'panel.layerComps', checkable: true },
      { label: 'Layers', cmd: 'panel.layers', shortcut: 'F7', checkable: true, done: true },
      { label: 'Navigator', cmd: 'panel.navigator', checkable: true, done: true },
      { label: 'Notes', cmd: 'panel.notes', checkable: true },
      { label: 'Paragraph', cmd: 'panel.paragraph', checkable: true },
      { label: 'Paragraph Styles', cmd: 'panel.paragraphStyles', checkable: true },
      { label: 'Paths', cmd: 'panel.paths', checkable: true, done: true },
      { label: 'Patterns', cmd: 'panel.patterns', checkable: true },
      { label: 'Properties', cmd: 'panel.properties', checkable: true, done: true },
      { label: 'Shapes', cmd: 'panel.shapes', checkable: true },
      { label: 'Styles', cmd: 'panel.styles', checkable: true },
      { label: 'Swatches', cmd: 'panel.swatches', checkable: true, done: true },
      { label: 'Timeline', cmd: 'panel.timeline', checkable: true },
      { label: 'Tool Presets', cmd: 'panel.toolPresets', checkable: true },
      sep,
      { label: 'Options', cmd: 'panel.options', checkable: true, done: true },
      { label: 'Tools', cmd: 'panel.tools', checkable: true, done: true },
      { label: 'Contextual Task Bar', cmd: 'panel.contextualTaskBar', checkable: true },
    ],
  },
  {
    label: 'Help',
    items: [
      { label: 'Umbra Help', cmd: 'help.help', shortcut: 'F1' },
      { label: 'Keyboard Shortcut Reference', cmd: 'help.shortcuts', done: true },
      { label: "What's New", cmd: 'help.whatsNew' },
      sep,
      { label: 'System Info…', cmd: 'help.systemInfo', done: true },
      { label: 'GPU Compatibility…', cmd: 'help.gpuInfo', done: true },
      sep,
      { label: 'About Umbra…', cmd: 'help.about', done: true },
    ],
  },
];

/** Flattened command index, for the keymap and the command palette. */
export interface CommandInfo {
  cmd: string;
  label: string;
  path: string[];
  shortcut?: string;
  done: boolean;
}

export const COMMANDS: CommandInfo[] = (() => {
  const out: CommandInfo[] = [];
  const visit = (nodes: MenuNode[], path: string[]) => {
    for (const n of nodes) {
      if (n.separator) continue;
      const here = [...path, n.label ?? ''];
      if (n.items) visit(n.items, here);
      else if (n.cmd) out.push({ cmd: n.cmd, label: n.label ?? n.cmd, path, shortcut: n.shortcut, done: !!n.done });
    }
  };
  for (const m of MENUS) visit(m.items, [m.label]);
  return out;
})();

export const COMMAND_BY_ID = new Map(COMMANDS.map((c) => [c.cmd, c]));
